"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def fibonacci(max_value):
    fib_n_1 = 1
    fib_n_2 = 2
    fib_even_val = []

    if fib_n_1 % 2 == 0:
        fib_even_val.append(fib_n_1)
    if fib_n_2 % 2 == 0:
        fib_even_val.append(fib_n_2)

    while fib_n_2 < max_value:
        
        fib_n = fib_n_1 + fib_n_2
        fib_n_1 = fib_n_2
        fib_n_2 = fib_n

        if fib_n % 2 == 0:
            fib_even_val.append(fib_n)
    print fib_even_val

    sum_fib_even = sum(fib_even_val)

    print sum_fib_even

fibonacci(89)
fibonacci(4000000)
